openapi: 3.1.0
info:
  title: Jungle NDVI Explorer API
  version: 1.0.0
paths:
  /ndvi:
    get:
      summary: Analyze an NDVI GeoTIFF file from a given URL and return basic NDVI statistics.
      parameters:
        - name: url
          in: query
          required: true
          description: Public URL of the GeoTIFF file to analyze.
          schema:
            type: string
      responses:
        '200':
          description: NDVI analysis completed successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  mean_ndvi:
                    type: number
                    description: Mean NDVI value of the analyzed image.
                  pixel_count:
                    type: integer
                    description: Number of pixels included in the NDVI calculation.
