info:
  title: Jungle NDVI Explorer API
  version: 1.0.0
openapi: 3.1.0
paths:
  /ndvi:
    get:
      parameters:
      - description: 解析対象となるGeoTIFFファイルのURL
        in: query
        name: url
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  mean_ndvi:
                    description: 平均NDVI値
                    type: number
                  pixel_count:
                    description: 解析対象ピクセル数
                    type: integer
                type: object
          description: 正常に解析が完了した場合
      summary: NDVI GeoTIFFファイルを解析して統計値を返す
