openapi: 3.1.0
info:
  title: Jungle NDVI Explorer API
  version: 1.0.0
servers:
  - url: "https://kg-ninja.github.io/KGchallengedskill/mock"
paths:
  /ndvi.json:
    get:
      summary: Get mock NDVI data
      description: Returns a fixed NDVI response for testing.
      operationId: getNdviMock
      responses:
        '200':
          description: NDVI statistics
          content:
            application/json:
              schema:
                type: object
                properties:
                  mean_ndvi:
                    type: number
                    description: Mean NDVI value
                  pixel_count:
                    type: integer
                    description: Number of pixels analyzed
