openapi: 3.1.0
info:
  title: Jungle NDVI Explorer API
  version: 1.0.0
paths:
  /ndvi:
    get:
      summary: NDVI GeoTIFFファイルを解析して統計値を返す
      parameters:
        - name: url
          in: query
          required: true
          description: 解析対象となるGeoTIFFファイルのURL
          schema:
            type: string
      responses:
        '200':
          description: 正常に解析が完了した場合
          content:
            application/json:
              schema:
                type: object
                properties:
                  mean_ndvi:
                    type: number
                    description: 平均NDVI値
                  pixel_count:
                    type: integer
                    description: 解析対象ピクセル数
