openapi: 3.1.0
info:
  title: Jungle NDVI Explorer API
  version: 1.0.0
servers:
  - url: "servers:
  - url: "https://ndvi-mock.free.beeceptor.com"
"
paths:
  /ndvi:
    get:
      summary: Analyze NDVI from GeoTIFF
      description: Returns mean NDVI and pixel count from a GeoTIFF file URL.
      parameters:
        - in: query
          name: url
          required: true
          description: URL of the GeoTIFF file to analyze
          schema:
            type: string
      responses:
        '200':
          description: NDVI statistics
          content:
            application/json:
              schema:
                type: object
                properties:
                  mean_ndvi:
                    type: number
                    description: Mean NDVI value
                  pixel_count:
                    type: integer
                    description: Number of pixels analyzed
