name: AIEO Memory Update & Deploy

on:
  schedule:
    # 毎日午前3時（UTC）に実行
    - cron: '0 3 * * *'
  workflow_dispatch:  # 手動トリガーも可能

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  update-memory:
    runs-on: ubuntu-latest
    
    steps:
      # 1. リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # 2. Python環境をセットアップ
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      
      # 3. 依存パッケージをインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # 4. メモリデータ取得スクリプトを実行
      - name: Fetch and update AIEO memory
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GOOGLE_CX: ${{ secrets.GOOGLE_CX }}
        run: |
          python scripts/update_aieo_memory.py
      
      # 5. 可視化スクリプトを実行（HTMLレポート生成）
      - name: Generate visualization HTML
        run: |
          python scripts/generate_visualization.py
      
      # 6. Git設定とコミット
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "AIEO Bot"
          git add -A
          git commit -m "chore: Update AIEO memory and visualization - $(date -u +'%Y-%m-%d %H:%M:%S UTC')" || echo "No changes to commit"
          git push
      
      # 7. GitHub Pages にデプロイ
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          cname: aieo-memory.example.com  # カスタムドメイン使用時のみ指定
